#[doc = "Register `QUERY_ERROR` reader"]
pub type R = crate::R<QueryErrorSpec>;
#[doc = "Field `QUERY_CHECK` reader - Represents whether or not an HMAC key matches the purpose. \\\\0: Match \\\\1: Error"]
pub type QueryCheckR = crate::BitReader;
impl R {
    #[doc = "Bit 0 - Represents whether or not an HMAC key matches the purpose. \\\\0: Match \\\\1: Error"]
    #[inline(always)]
    pub fn query_check(&self) -> QueryCheckR {
        QueryCheckR::new((self.bits & 1) != 0)
    }
}
#[doc = "Stores matching results between keys generated by users and corresponding purposes\n\nYou can [`read`](crate::Reg::read) this register and get [`query_error::R`](R). See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct QueryErrorSpec;
impl crate::RegisterSpec for QueryErrorSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`query_error::R`](R) reader structure"]
impl crate::Readable for QueryErrorSpec {}
#[doc = "`reset()` method sets QUERY_ERROR to value 0"]
impl crate::Resettable for QueryErrorSpec {}
