[target.riscv32imafc-unknown-none-elf]
runner = "espflash flash --monitor --chip esp32p4 --flash-size 16mb --flash-mode qio --flash-freq 80mhz --partition-table partitions.csv"
rustflags = ["-C", "link-arg=-Tmemory.x", "-C", "link-arg=-Tlink.x"]

[build]
target = "riscv32imafc-unknown-none-elf"
