#[doc = "Register `RX_GENRL_CFG` reader"]
pub type R = crate::R<RxGenrlCfgSpec>;
#[doc = "Register `RX_GENRL_CFG` writer"]
pub type W = crate::W<RxGenrlCfgSpec>;
#[doc = "Field `RX_GATING_EN` reader - Write 1 to enable the clock gating of output rx clock."]
pub type RxGatingEnR = crate::BitReader;
#[doc = "Field `RX_GATING_EN` writer - Write 1 to enable the clock gating of output rx clock."]
pub type RxGatingEnW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `RX_TIMEOUT_THRES` reader - Configures threshold of timeout counter."]
pub type RxTimeoutThresR = crate::FieldReader<u16>;
#[doc = "Field `RX_TIMEOUT_THRES` writer - Configures threshold of timeout counter."]
pub type RxTimeoutThresW<'a, REG> = crate::FieldWriter<'a, REG, 16, u16>;
#[doc = "Field `RX_TIMEOUT_EN` reader - Write 1 to enable timeout function to generate error eof."]
pub type RxTimeoutEnR = crate::BitReader;
#[doc = "Field `RX_TIMEOUT_EN` writer - Write 1 to enable timeout function to generate error eof."]
pub type RxTimeoutEnW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `RX_EOF_GEN_SEL` reader - Configures the DMA eof generated mechanism. 1'b0: eof generated by data bit length. 1'b1: eof generated by external enable signal."]
pub type RxEofGenSelR = crate::BitReader;
#[doc = "Field `RX_EOF_GEN_SEL` writer - Configures the DMA eof generated mechanism. 1'b0: eof generated by data bit length. 1'b1: eof generated by external enable signal."]
pub type RxEofGenSelW<'a, REG> = crate::BitWriter<'a, REG>;
impl R {
    #[doc = "Bit 12 - Write 1 to enable the clock gating of output rx clock."]
    #[inline(always)]
    pub fn rx_gating_en(&self) -> RxGatingEnR {
        RxGatingEnR::new(((self.bits >> 12) & 1) != 0)
    }
    #[doc = "Bits 13:28 - Configures threshold of timeout counter."]
    #[inline(always)]
    pub fn rx_timeout_thres(&self) -> RxTimeoutThresR {
        RxTimeoutThresR::new(((self.bits >> 13) & 0xffff) as u16)
    }
    #[doc = "Bit 29 - Write 1 to enable timeout function to generate error eof."]
    #[inline(always)]
    pub fn rx_timeout_en(&self) -> RxTimeoutEnR {
        RxTimeoutEnR::new(((self.bits >> 29) & 1) != 0)
    }
    #[doc = "Bit 30 - Configures the DMA eof generated mechanism. 1'b0: eof generated by data bit length. 1'b1: eof generated by external enable signal."]
    #[inline(always)]
    pub fn rx_eof_gen_sel(&self) -> RxEofGenSelR {
        RxEofGenSelR::new(((self.bits >> 30) & 1) != 0)
    }
}
impl W {
    #[doc = "Bit 12 - Write 1 to enable the clock gating of output rx clock."]
    #[inline(always)]
    pub fn rx_gating_en(&mut self) -> RxGatingEnW<'_, RxGenrlCfgSpec> {
        RxGatingEnW::new(self, 12)
    }
    #[doc = "Bits 13:28 - Configures threshold of timeout counter."]
    #[inline(always)]
    pub fn rx_timeout_thres(&mut self) -> RxTimeoutThresW<'_, RxGenrlCfgSpec> {
        RxTimeoutThresW::new(self, 13)
    }
    #[doc = "Bit 29 - Write 1 to enable timeout function to generate error eof."]
    #[inline(always)]
    pub fn rx_timeout_en(&mut self) -> RxTimeoutEnW<'_, RxGenrlCfgSpec> {
        RxTimeoutEnW::new(self, 29)
    }
    #[doc = "Bit 30 - Configures the DMA eof generated mechanism. 1'b0: eof generated by data bit length. 1'b1: eof generated by external enable signal."]
    #[inline(always)]
    pub fn rx_eof_gen_sel(&mut self) -> RxEofGenSelW<'_, RxGenrlCfgSpec> {
        RxEofGenSelW::new(self, 30)
    }
}
#[doc = "Parallel RX general configuration register.\n\nYou can [`read`](crate::Reg::read) this register and get [`rx_genrl_cfg::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`rx_genrl_cfg::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct RxGenrlCfgSpec;
impl crate::RegisterSpec for RxGenrlCfgSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`rx_genrl_cfg::R`](R) reader structure"]
impl crate::Readable for RxGenrlCfgSpec {}
#[doc = "`write(|w| ..)` method takes [`rx_genrl_cfg::W`](W) writer structure"]
impl crate::Writable for RxGenrlCfgSpec {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets RX_GENRL_CFG to value 0x21ff_e000"]
impl crate::Resettable for RxGenrlCfgSpec {
    const RESET_VALUE: u32 = 0x21ff_e000;
}
