#[doc = "Register `CONF` reader"]
pub type R = crate::R<ConfSpec>;
#[doc = "Register `CONF` writer"]
pub type W = crate::W<ConfSpec>;
#[doc = "Field `WORK_MODE` reader - The work mode bits of ECDSA Accelerator. 0: Signature Verify Mode. 1: Signature Generate Mode. 2: Export Public Key Mode. 3: invalid."]
pub type WorkModeR = crate::FieldReader;
#[doc = "Field `WORK_MODE` writer - The work mode bits of ECDSA Accelerator. 0: Signature Verify Mode. 1: Signature Generate Mode. 2: Export Public Key Mode. 3: invalid."]
pub type WorkModeW<'a, REG> = crate::FieldWriter<'a, REG, 2>;
#[doc = "Field `ECC_CURVE` reader - The ecc curve select bit of ECDSA Accelerator. 0: P-192. 1: P-256. 2: P-384."]
pub type EccCurveR = crate::FieldReader;
#[doc = "Field `ECC_CURVE` writer - The ecc curve select bit of ECDSA Accelerator. 0: P-192. 1: P-256. 2: P-384."]
pub type EccCurveW<'a, REG> = crate::FieldWriter<'a, REG, 2>;
#[doc = "Field `SOFTWARE_SET_K` reader - The source of k select bit. 0: k is automatically generated by hardware. 1: k is written by software."]
pub type SoftwareSetKR = crate::BitReader;
#[doc = "Field `SOFTWARE_SET_K` writer - The source of k select bit. 0: k is automatically generated by hardware. 1: k is written by software."]
pub type SoftwareSetKW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `SOFTWARE_SET_Z` reader - The source of z select bit. 0: z is generated from SHA result. 1: z is written by software."]
pub type SoftwareSetZR = crate::BitReader;
#[doc = "Field `SOFTWARE_SET_Z` writer - The source of z select bit. 0: z is generated from SHA result. 1: z is written by software."]
pub type SoftwareSetZW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `DETERMINISTIC_K` reader - The source of hardware generated k. 0: k is generated by TRNG. 1: k is generated by deterministic derivation algorithm."]
pub type DeterministicKR = crate::BitReader;
#[doc = "Field `DETERMINISTIC_K` writer - The source of hardware generated k. 0: k is generated by TRNG. 1: k is generated by deterministic derivation algorithm."]
pub type DeterministicKW<'a, REG> = crate::BitWriter<'a, REG>;
impl R {
    #[doc = "Bits 0:1 - The work mode bits of ECDSA Accelerator. 0: Signature Verify Mode. 1: Signature Generate Mode. 2: Export Public Key Mode. 3: invalid."]
    #[inline(always)]
    pub fn work_mode(&self) -> WorkModeR {
        WorkModeR::new((self.bits & 3) as u8)
    }
    #[doc = "Bits 2:3 - The ecc curve select bit of ECDSA Accelerator. 0: P-192. 1: P-256. 2: P-384."]
    #[inline(always)]
    pub fn ecc_curve(&self) -> EccCurveR {
        EccCurveR::new(((self.bits >> 2) & 3) as u8)
    }
    #[doc = "Bit 4 - The source of k select bit. 0: k is automatically generated by hardware. 1: k is written by software."]
    #[inline(always)]
    pub fn software_set_k(&self) -> SoftwareSetKR {
        SoftwareSetKR::new(((self.bits >> 4) & 1) != 0)
    }
    #[doc = "Bit 5 - The source of z select bit. 0: z is generated from SHA result. 1: z is written by software."]
    #[inline(always)]
    pub fn software_set_z(&self) -> SoftwareSetZR {
        SoftwareSetZR::new(((self.bits >> 5) & 1) != 0)
    }
    #[doc = "Bit 6 - The source of hardware generated k. 0: k is generated by TRNG. 1: k is generated by deterministic derivation algorithm."]
    #[inline(always)]
    pub fn deterministic_k(&self) -> DeterministicKR {
        DeterministicKR::new(((self.bits >> 6) & 1) != 0)
    }
}
impl W {
    #[doc = "Bits 0:1 - The work mode bits of ECDSA Accelerator. 0: Signature Verify Mode. 1: Signature Generate Mode. 2: Export Public Key Mode. 3: invalid."]
    #[inline(always)]
    pub fn work_mode(&mut self) -> WorkModeW<'_, ConfSpec> {
        WorkModeW::new(self, 0)
    }
    #[doc = "Bits 2:3 - The ecc curve select bit of ECDSA Accelerator. 0: P-192. 1: P-256. 2: P-384."]
    #[inline(always)]
    pub fn ecc_curve(&mut self) -> EccCurveW<'_, ConfSpec> {
        EccCurveW::new(self, 2)
    }
    #[doc = "Bit 4 - The source of k select bit. 0: k is automatically generated by hardware. 1: k is written by software."]
    #[inline(always)]
    pub fn software_set_k(&mut self) -> SoftwareSetKW<'_, ConfSpec> {
        SoftwareSetKW::new(self, 4)
    }
    #[doc = "Bit 5 - The source of z select bit. 0: z is generated from SHA result. 1: z is written by software."]
    #[inline(always)]
    pub fn software_set_z(&mut self) -> SoftwareSetZW<'_, ConfSpec> {
        SoftwareSetZW::new(self, 5)
    }
    #[doc = "Bit 6 - The source of hardware generated k. 0: k is generated by TRNG. 1: k is generated by deterministic derivation algorithm."]
    #[inline(always)]
    pub fn deterministic_k(&mut self) -> DeterministicKW<'_, ConfSpec> {
        DeterministicKW::new(self, 6)
    }
}
#[doc = "ECDSA configure register\n\nYou can [`read`](crate::Reg::read) this register and get [`conf::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`conf::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct ConfSpec;
impl crate::RegisterSpec for ConfSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`conf::R`](R) reader structure"]
impl crate::Readable for ConfSpec {}
#[doc = "`write(|w| ..)` method takes [`conf::W`](W) writer structure"]
impl crate::Writable for ConfSpec {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets CONF to value 0"]
impl crate::Resettable for ConfSpec {}
